//
// Created by James on 10/26/2019.
//

#ifndef BEHOLDER_STDINC_HPP
#define BEHOLDER_STDINC_HPP

#define BEHOLDER_VERSION_MAJOR @Beholder_VERSION_MAJOR@
#define BEHOLDER_VERSION_MINOR @Beholder_VERSION_MINOR@

#endif //BEHOLDER_STDINC_HPP
